name: Build and test

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag geometry_common:$(date +%s) --no-cache
    - name: Build doxygen documentation
      uses: mattnotmitt/doxygen-action@1.9.5
      with:
        doxyfile-path: docs/doxygen/Doxyfile.in
        working-directory: docs/
